POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "With login, part2",
  "author": "Vladyslav Ostapchuk",
  "url": "https://google.com/",
  "likes": 4,
  "userId": "62ef10c86168c9c7de451389"
}