POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "My programming Journey to the West",
  "author": "Vladyslav Ostapchuk",
  "url": "https://github.com/VladyslavOstapchuk0/FullStackOpen/",
  "likes": 1000
}