PUT http://localhost:3003/api/blogs/62ef3a7b4b8909d7911a246c
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlZsYWR5c2xhdk9zdGFwY2h1azAiLCJpZCI6IjYyZWYzNTYyNTQ3ZWY4M2M3MTI4NzFmMSIsImlhdCI6MTY1OTg0Mzk5MywiZXhwIjoxNjU5ODQ3NTkzfQ.pwsfJAHZf84nHZMJFoOkiVmmF10b04Xwv1jqZP5MNjc

{
  "title": "With login, updated",
  "author": "Vladyslav Ostapchuk",
  "url": "https://google7.com/",
  "likes": 27
}